# Task 1
### Write a NumPy program to create an array of all even integers from 30 to 70.


In [14]:
import numpy as np

even_array = np.arange(30, 71, 2)

print(even_array)


[30 32 34 36 38 40 42 44 46 48 50 52 54 56 58 60 62 64 66 68 70]


# Task 2
### Write a NumPy program to generate an array of 15 random numbers from a standard normal distribution

In [2]:
random_numbers = np.random.normal(size=15)

print(random_numbers)

[ 0.31909074  0.37663582  0.23793411 -0.76882536 -0.798168   -0.97561957
 -0.68538963 -0.84295161 -2.21358732 -1.20688991  0.69503668  0.76193894
 -0.50429912 -0.30181239 -2.33429536]


# Task 3
### How to compute the cross-product of two matrices in NumPy?

In [6]:

arr1 = np.array([[1, 2],
                [3, 4]])

arr2 = np.array([[5, 5],
                [6, 6]])

cross_product = np.cross(arr1, arr2)

print("Cross-product matrix:")

print(cross_product)


Cross-product matrix:
[-5 -6]


# Task 4
### How to compute the determinant of an array using NumPy?

In [8]:
matrix = np.array([[1, 2],
                   [4, 5]])

determinant_value = np.linalg.det(matrix)

print("Determinant:", determinant_value)


Determinant: -2.9999999999999996


# Task 5
### How to create a 3x3x3 array with random values using NumPy?


In [10]:
random_array = np.random.rand(3, 3, 3) * 9 + 1

print(random_array)


[[[6.55338362 6.43093948 9.33463185]
  [3.12343624 5.57874821 5.9731622 ]
  [4.05835232 3.71765095 1.64332849]]

 [[5.70039502 1.00335245 8.4426836 ]
  [4.79473163 2.82382575 2.83541369]
  [8.48955217 2.21000006 9.13249627]]

 [[9.91503566 8.26228032 5.26756015]
  [3.07633701 3.95833754 4.22135254]
  [3.06676697 4.24015706 2.68220355]]]


# Task 6
### How to create a 5x5 array with random values and find the minimum and maximum values using NumPy?


In [12]:
random_array = np.random.rand(5, 5) * 9 + 1

print("Random Array:")
print(random_array)

min_value = np.min(random_array)
max_value = np.max(random_array)

print("Minimum Value:", min_value)
print("Maximum Value:", max_value)


Random Array:
[[9.76589437 5.00411444 4.8486819  5.29154986 9.72441511]
 [3.26185311 4.23691114 9.59830033 8.89755823 3.06037038]
 [1.51182652 5.48962893 9.69034067 1.33018395 2.6596911 ]
 [1.14648577 4.2613942  6.77548618 6.55255155 1.14280413]
 [8.51220533 5.99388551 3.05996713 1.99887344 2.24331251]]
Minimum Value: 1.1428041262476998
Maximum Value: 9.765894373933673


# Task 7
### How to compute the mean, standard deviation, and variance of a given array along the second axis in NumPy?

In [13]:
sample_array = np.array([[1, 2],
                         [4, 5]])

mean_values = np.mean(sample_array, axis=1)

std_deviation_values = np.std(sample_array, axis=1)

variance_values = np.var(sample_array, axis=1)

print("Mean along second axis:", mean_values)
print("Standard Deviation along second axis:", std_deviation_values)
print("Variance along second axis:", variance_values)


Mean along second axis: [1.5 4.5]
Standard Deviation along second axis: [0.5 0.5]
Variance along second axis: [0.25 0.25]
